# Generated by Django 4.2.16 on 2024-12-10 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='開催日時')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='繰り返しON/OFF')),
                ('recurrence_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='繰り返し日数')),
                ('is_recordable', models.BooleanField(default=False, verbose_name='録画可否')),
                ('meeting_name', models.CharField(default='random-79c464b3-4aec-4d85-b2a8-06ee5ba47e40', max_length=255, verbose_name='会議名')),
                ('meeting_id', models.CharField(default='random-26ade0d0-9b4c-4467-861c-cde2fd8e4ff9', max_length=255, unique=True, verbose_name='会議ID')),
                ('attendee_pw', models.CharField(default='ap', max_length=255, verbose_name='参加者パスワード')),
                ('moderator_pw', models.CharField(default='mp', max_length=255, verbose_name='モデレーターパスワード')),
                ('welcome', models.TextField(default='welcome to the meeting!!', verbose_name='ウェルカムメッセージ')),
                ('record', models.BooleanField(default=True, verbose_name='録画有効化')),
                ('guest_policy', models.CharField(default='ASK_MODERATOR', max_length=50, verbose_name='ゲストポリシー')),
                ('notify_record_is_on', models.BooleanField(default=True, verbose_name='録画中通知')),
                ('full_name', models.CharField(default='John Doe', max_length=255, verbose_name='フルネーム')),
                ('guest', models.BooleanField(default=True, verbose_name='ゲスト')),
                ('record_id', models.CharField(default='12345', max_length=255, verbose_name='録画ID')),
                ('publish', models.BooleanField(default=True, verbose_name='公開フラグ')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会議作成者')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='source.meeting', verbose_name='会議')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='関連ユーザー')),
            ],
        ),
    ]
