# Generated by Django 4.2.16 on 2024-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_meeting_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-f6f01670-39b2-4213-9e2c-bc652a29d609', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-338fd80f-e99d-44c3-a710-653aa01a0419', max_length=255, verbose_name='会議名'),
        ),
    ]
