# Generated by Django 4.2.16 on 2024-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.IntegerField(default=114514, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-d70c1c1b-59b6-4ee3-91c6-76a7e6ce9156', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-f410da20-4f65-4a85-b6b7-7213ca044569', max_length=255, verbose_name='会議名'),
        ),
    ]
