# Generated by Django 4.2.16 on 2024-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_meeting_create_time_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-16ca9285-1958-45f6-8179-8d9187de9701', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-f4486fea-5480-4c7d-a85f-461fba4fe806', max_length=255, verbose_name='会議名'),
        ),
    ]
