# Generated by Django 4.2.16 on 2024-12-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-30ae1e51-f509-45dd-a243-dbffbca3bbbf', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-70822d39-1a3d-4e43-b75e-0fe1b803b83c', max_length=255, verbose_name='会議名'),
        ),
    ]
