# Generated by Django 4.2.16 on 2024-12-10 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-e88d78d4-38d4-4873-a0bb-3a3bb6a846c0', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-07d5a4e5-67fa-41f9-84a5-b5e967e48ccf', max_length=255, verbose_name='会議名'),
        ),
    ]
