# Generated by Django 4.2.16 on 2024-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_meeting_created_date_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-7ea5b8fa-8b85-42e0-b133-d3bd3ef79fbc', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-613de60f-951e-4eba-b64f-0a669513dca7', max_length=255, verbose_name='会議名'),
        ),
    ]
