# Generated by Django 4.2.1 on 2025-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-bbf90b87-282d-4898-a9f5-4ea2eb691716', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-b54c7bb9-cf33-4c91-999d-081983b1e2a5', max_length=255, verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='record',
            field=models.BooleanField(default=True, null=True, verbose_name='録画有効化'),
        ),
    ]
