# Generated by Django 4.2.1 on 2025-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='is_recordable',
            new_name='is_record',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='record',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-d6200017-0337-44b2-90b0-e74ca2f933a8', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-62cfe101-69a8-48c3-b384-9a7cdd9b50f1', max_length=255, verbose_name='会議名'),
        ),
    ]
