# Generated by Django 4.2.16 on 2025-01-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_rename_is_recordable_meeting_is_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-295670de-d5fc-4629-88a1-063af9490f6f', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-5ef8e043-91e5-449b-9a7c-fae8a442a998', max_length=255, verbose_name='会議名'),
        ),
    ]
