# Generated by Django 4.2.16 on 2025-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-33dc90fe-23be-490a-a5ac-42ff099d686f', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-9945f64e-4480-48b0-8a09-e72c94092e50', max_length=255, verbose_name='会議名'),
        ),
    ]
