# Generated by Django 4.2.16 on 2025-01-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-800e3c4f-4267-49af-b5fa-805ebac85811', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-74ebb870-3afb-4c61-b54e-e143b86f7519', max_length=255, verbose_name='会議名'),
        ),
    ]
