# Generated by Django 4.2.16 on 2025-01-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-c99758f6-8c4a-44f8-a3c8-ba8cdd75f4fa', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-e88d8df1-ce3e-4186-91ed-48e9c8f5a7ba', max_length=255, verbose_name='会議名'),
        ),
    ]
