# Generated by Django 4.2.16 on 2025-01-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-0a748830-f7ea-41b2-8265-5b943b9652b3', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-fceba73f-f69f-44cf-910d-4b8a94d2a518', max_length=255, verbose_name='会議名'),
        ),
    ]
