# Generated by Django 4.2.16 on 2025-01-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-0eb998ef-b198-410b-9bab-2349747791ae', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-89437983-2cca-478d-b43e-86e780a75cb9', max_length=255, verbose_name='会議名'),
        ),
    ]
