# Generated by Django 4.2.1 on 2025-01-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-551e4baf-33db-4e95-bca3-61a117e49d22', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3f60c855-6c1f-4e45-b94a-38c6ff674e52', max_length=255, verbose_name='会議名'),
        ),
    ]
