# Generated by Django 4.2.1 on 2025-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-61740990-675e-481e-9bac-d66954ce3108', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-fbfcb37f-3c2f-4369-9854-df4bfbbeee1f', max_length=255, verbose_name='会議名'),
        ),
    ]
