# Generated by Django 4.2.16 on 2025-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-1fa8a318-bec2-460a-a9de-f0c1df0255bb', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-34101def-e9d4-4881-a41f-b2e391af2619', max_length=255, verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurrence_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='繰り返し日数'),
        ),
    ]
