# Generated by Django 4.2.16 on 2025-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-47f7b504-f918-441e-bd8e-b411e1e34a37', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-73791f55-97ac-47a4-ab20-e27922cba05e', max_length=255, verbose_name='会議名'),
        ),
    ]
