# Generated by Django 4.2.16 on 2025-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-80cd93a2-fecd-4a1a-8ff1-095eb642c144', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-54c5e4d1-935e-469e-b78b-32461a6e8c44', max_length=255, verbose_name='会議名'),
        ),
    ]
