# Generated by Django 4.2.1 on 2025-01-31 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0021_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ad2a16de-08ec-4d94-a175-87a8b7d8a9e9', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3ddbeef7-eeef-4f41-9f58-c7c90ee1b0d2', max_length=255, verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='welcome',
            field=models.TextField(default='welcome!!', verbose_name='ウェルカムメッセージ'),
        ),
        migrations.CreateModel(
            name='Notification_Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_error', models.BooleanField(default=False, verbose_name='エラー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
