# Generated by Django 4.2.16 on 2025-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0022_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-1b154416-f67e-41a9-8114-22050c0c8f09', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-d6ab8164-8983-4ad3-956e-ce81d2761cdc', max_length=255, verbose_name='会議名'),
        ),
    ]
