# Generated by Django 4.2.16 on 2025-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0023_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-900db726-887a-4a46-95df-f8d6b29b5d1b', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-f1d13633-8b7a-4009-be6b-e3dee0ed906e', max_length=255, verbose_name='会議名'),
        ),
    ]
