# Generated by Django 4.2.16 on 2025-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0024_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-f0b1a21f-03f8-4453-bcdd-df05d688a2df', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-15656182-4d81-470d-8395-a40c20c706fa', max_length=255, verbose_name='会議名'),
        ),
    ]
