# Generated by Django 4.2.16 on 2025-02-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0025_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-8b277307-7bf7-45fe-a609-a91e54f15ae9', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-66450984-98e7-4065-952c-849fcb5d93df', max_length=255, verbose_name='会議名'),
        ),
    ]
