# Generated by Django 4.2.16 on 2025-02-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0026_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-78df0fc8-dd90-47d3-9c68-5ac396b5dd2a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-39b89ec1-612c-46d2-924e-320ebf8c5482', max_length=255, verbose_name='会議名'),
        ),
    ]
