# Generated by Django 4.2.16 on 2025-02-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0027_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-7dbea78b-2bb7-4f6a-ab98-d9f889f6855f', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-f0d1efa6-b027-464a-9e38-9b0c5ecd9938', max_length=255, verbose_name='会議名'),
        ),
    ]
