# Generated by Django 4.2.16 on 2025-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0028_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-4fd7cc7e-07e2-446c-861d-c8ec24d123bc', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-b44f217b-8fee-463f-a62c-ce0e77e9f164', max_length=255, verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='moderator_pw',
            field=models.CharField(default='mopa2025', max_length=255, verbose_name='モデレーターパスワード'),
        ),
    ]
