# Generated by Django 4.2.1 on 2025-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0029_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-59bd4504-6508-4dd1-9e54-4d12b6138320', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-8d6ba716-7445-42ea-85ae-b41c2a45b454', max_length=255, verbose_name='会議名'),
        ),
    ]
