# Generated by Django 4.2.1 on 2025-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0030_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-e41ca617-2268-409e-980f-8331dcebe87c', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-c119a41e-a523-47c8-bd11-dabffd7f904f', max_length=255, verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurrence_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='繰り返し日数'),
        ),
    ]
