# Generated by Django 4.2.1 on 2025-02-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0031_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-3b1b9c3c-50e6-49ed-b931-31ece7d435ac', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3ea7840c-26a0-46c2-a45d-a07ce877ac2e', max_length=255, verbose_name='会議名'),
        ),
    ]
