# Generated by Django 4.2.1 on 2025-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0032_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-cc864752-f709-40df-a646-4468c5a60690', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-c7701367-d428-47e9-894a-e286d34c68b5', max_length=255, verbose_name='会議名'),
        ),
    ]
