# Generated by Django 4.2.16 on 2025-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0033_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-57f697a7-9557-4b2e-a92f-0c4600f969c2', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-2a12ef3a-70e6-491b-91e0-58268497b915', max_length=255, verbose_name='会議名'),
        ),
    ]
