# Generated by Django 4.2.16 on 2025-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0034_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済みフラグ'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='実施済みフラグ'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-052c2d54-a77d-4a5e-b7ac-90239aae1277', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-4e9689bc-4059-4019-9d38-0383023a80a0', max_length=255, verbose_name='会議名'),
        ),
    ]
