# Generated by Django 4.2.16 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0035_meeting_is_deleted_meeting_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ef1f5664-781e-4d00-bbf7-a1477d092bec', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-eec2e61a-61d2-4e87-bba3-de47d7eeea3d', max_length=255, verbose_name='会議名'),
        ),
    ]
