# Generated by Django 4.2.16 on 2025-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0036_alter_customuser_last_login_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_recurring_done',
            field=models.BooleanField(default=False, verbose_name='繰り返し済みフラグ'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-dc326377-1ac3-4dbb-9929-7f470d4cd1b9', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-e9edada7-e6a5-4bca-a6a7-f5e5e3d1802a', max_length=255, verbose_name='会議名'),
        ),
    ]
