# Generated by Django 4.2.16 on 2025-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0037_meeting_is_recurring_done_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.BigIntegerField(default=114514, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-bcfc08dd-a99a-4fd8-9a99-9c5cfb54a314', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-64c58f76-f380-4c09-bb7b-53567fffed75', max_length=255, verbose_name='会議名'),
        ),
    ]
