# Generated by Django 4.2.16 on 2025-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0038_alter_meeting_create_time_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-37598b0d-62fc-42d2-b4ea-7fac79f0317e', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-0932780b-7597-457f-94bf-e973d72b3ac2', max_length=255, verbose_name='会議名'),
        ),
    ]
