# Generated by Django 4.2.16 on 2025-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0039_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mail_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='メールテンプレート'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mail_title',
            field=models.CharField(default='会議情報通知 TerakoyaOnline', max_length=255, verbose_name='メールタイトル'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a510c6b1-c3ec-4c47-ab12-78e92fe74a78', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3bfddfd8-265c-4988-84ca-cb3189bc1c6b', max_length=255, verbose_name='会議名'),
        ),
    ]
