# Generated by Django 4.2.16 on 2025-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0040_meeting_mail_text_meeting_mail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ad087b7f-fa94-49dd-87ef-1810ef476d8f', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-a1996892-9684-4190-9349-7024d33e8a58', max_length=255, verbose_name='会議名'),
        ),
    ]
