# Generated by Django 4.2.16 on 2025-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0041_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-4328b7f0-3396-4032-9afc-ff4692809015', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-d816d9d9-f55f-4b22-9579-ee8d75a76e5b', max_length=255, verbose_name='会議名'),
        ),
    ]
