# Generated by Django 4.2.16 on 2025-05-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0042_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-8ca1f7da-d282-4b3b-900e-32f9696f184c', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-387e6dbe-5625-459a-8829-d4522ee21b8d', max_length=255, verbose_name='会議名'),
        ),
    ]
