# Generated by Django 4.2.16 on 2025-05-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0043_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='mail_text',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='mail_title',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-5efbdd81-803a-4481-a226-1df6d0a3ce9f', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-9d6a0c37-1745-4a23-b1f9-a64b485fe57f', max_length=255, verbose_name='会議名'),
        ),
    ]
