# Generated by Django 4.2.16 on 2025-05-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0044_remove_meeting_mail_text_remove_meeting_mail_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mail_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='メールテンプレート'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mail_title',
            field=models.CharField(default='会議情報通知 TerakoyaOnline', max_length=255, verbose_name='メールタイトル'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a93ff510-f398-43ce-854e-368de8c8736a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-de01558b-ac54-44e4-8133-8c113ff4f29d', max_length=255, verbose_name='会議名'),
        ),
    ]
