# Generated by Django 4.2.16 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0045_meeting_mail_text_meeting_mail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a26f1ae5-b8d1-4376-9919-5f654ea6c987', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3e5e7ddb-ede3-4076-bc6d-75dce5c07860', max_length=255, verbose_name='会議名'),
        ),
    ]
