# Generated by Django 4.2.16 on 2025-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0046_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-b1ca99c0-1eea-472e-9a38-577d2a3448c7', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-38f54194-939f-402e-879e-4df3a60885fe', max_length=255, verbose_name='会議名'),
        ),
    ]
