# Generated by Django 4.2.16 on 2025-05-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0047_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-bcb5a2c6-e016-4f1d-aa6e-bc3228a453f4', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3458d064-86fa-4371-bd6b-78213e324fe5', max_length=255, verbose_name='会議名'),
        ),
    ]
