# Generated by Django 4.2.16 on 2025-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0048_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-8e585def-8568-4d9d-bd47-3e766d2e2833', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-bcd7e80d-708a-45ff-b497-299a9838631d', max_length=255, verbose_name='会議名'),
        ),
    ]
