# Generated by Django 4.2.16 on 2025-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0049_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a7cc0416-717c-45a2-a2fa-de1f4712fb27', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-429ac019-332a-45c9-9dcb-af85207822bf', max_length=255, verbose_name='会議名'),
        ),
    ]
