# Generated by Django 4.2.16 on 2025-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0050_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-861d19c3-b371-42f2-b91a-91d3baf21517', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-c3e6a40b-16e7-446c-a727-d38aa8f1d854', max_length=255, verbose_name='会議名'),
        ),
    ]
