# Generated by Django 4.2.16 on 2025-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0051_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-d0fdb983-56c7-4004-bdfc-c9d951197e5e', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-13905791-6385-4411-8dc1-baaccafc5a89', max_length=255, verbose_name='会議名'),
        ),
    ]
