# Generated by Django 4.2.16 on 2025-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0052_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a02cab7d-da4b-4b7c-8886-762332500098', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-cc1469b6-4910-4937-aefb-f6d241e5c091', max_length=255, verbose_name='会議名'),
        ),
    ]
