# Generated by Django 4.2.16 on 2025-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0053_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-75c3eb6e-ab3f-456c-8273-85bf0d537895', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-2dc2e06c-d19d-48d9-82a1-f155b9bd01c0', max_length=255, verbose_name='会議名'),
        ),
    ]
