# Generated by Django 4.2.16 on 2025-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0054_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-c02cb776-6cef-450c-b6b5-239726d7f4e7', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-20282cba-a1a4-447b-9686-4201263e7a37', max_length=255, verbose_name='会議名'),
        ),
    ]
