# Generated by Django 4.2.16 on 2025-05-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0055_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-f80fe9dc-b417-4f46-ac40-c11a90973ec5', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-7a49e806-1403-4911-88f0-5413dc52d591', max_length=255, verbose_name='会議名'),
        ),
    ]
