# Generated by Django 4.2.16 on 2025-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0056_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-540c103a-7c3b-49c6-97d6-9e9e96a107a4', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-0d59154b-3b46-4c3c-b332-c703daba408c', max_length=255, verbose_name='会議名'),
        ),
    ]
