# Generated by Django 4.2.16 on 2025-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0057_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-8be88fe5-c7b7-48bf-a45a-ea0b88430be6', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-5586628d-4427-4bc9-a4a9-dee3e520d0f0', max_length=255, verbose_name='会議名'),
        ),
    ]
