# Generated by Django 4.2.16 on 2025-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0058_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.BigIntegerField(default=200, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-a6950d6c-406d-4344-8c5d-cd0f9d92530b', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-824becca-26a1-43d6-8373-b6be95a707d7', max_length=255, verbose_name='会議名'),
        ),
    ]
