# Generated by Django 4.2.16 on 2025-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0059_alter_meeting_create_time_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.BigIntegerField(default=114514, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-497abe6f-71d2-4436-b840-25aa2491693a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-b8924081-e218-4837-883d-91550d5c624a', max_length=255, verbose_name='会議名'),
        ),
    ]
