# Generated by Django 4.2.16 on 2025-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0060_alter_meeting_create_time_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_time',
            field=models.BigIntegerField(default=10, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-9425e6b1-9e52-406c-a88d-3a9a47181e39', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-94d2c487-e619-43ed-b2d7-50aab9dc409f', max_length=255, verbose_name='会議名'),
        ),
    ]
