# Generated by Django 4.2.16 on 2025-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0061_alter_meeting_create_time_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-90aff6e6-803f-4b45-b794-01ff9f84ec98', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3e2a0b23-0bd1-4a4e-9480-f6f5e638bc81', max_length=255, verbose_name='会議名'),
        ),
    ]
