# Generated by Django 4.2.16 on 2025-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0062_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-331d04ac-6f95-4ee6-811e-e6cf33f0a77a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-dc12eb28-1d19-4a8a-a971-f6d272d17185', max_length=255, verbose_name='会議名'),
        ),
    ]
