# Generated by Django 4.2.16 on 2025-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0063_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-88b8c2b8-15ce-4153-97c7-1dde4eb37dcc', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-bbb9d936-c2ff-4a87-83ef-107b7a571d3b', max_length=255, verbose_name='会議名'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['creator', 'date', 'is_deleted', 'is_done'], name='source_meet_creator_bdf7db_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'is_deleted', 'is_done'], name='source_meet_date_413d03_idx'),
        ),
    ]
