# Generated by Django 4.2.16 on 2025-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0064_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-9c7009bf-e30b-4ae2-a2fd-3b8e106762ff', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-40f6b513-d50c-4012-a6e0-02d630510123', max_length=255, verbose_name='会議名'),
        ),
    ]
