# Generated by Django 4.2.16 on 2025-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0065_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-17fd983e-fe94-4ca4-a1a9-08d85de93016', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-0ff5520f-bdd4-4816-b4be-9a97efb5c0e8', max_length=255, verbose_name='会議名'),
        ),
    ]
