# Generated by Django 4.2.16 on 2025-06-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0066_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ef6975b7-0d48-47fb-8c39-cc284f7103c5', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-2c01b502-3847-4b3e-b408-2a6821a59093', max_length=255, verbose_name='会議名'),
        ),
    ]
