# Generated by Django 4.2.16 on 2025-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0067_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-4114f3b4-2f77-491f-bc76-07f34b79da0a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-644da0a7-0bc5-4a99-bbcb-d05933c27d65', max_length=255, verbose_name='会議名'),
        ),
    ]
