# Generated by Django 4.2.16 on 2025-06-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0068_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-d1261ac5-df68-4e0e-aa01-7dc11fb4a75d', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-ea190e01-397d-4ec5-87ef-f18ef73e25a5', max_length=255, verbose_name='会議名'),
        ),
    ]
