# Generated by Django 4.2.16 on 2025-06-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0069_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-f337741e-20d7-4e49-ad83-a081b2afa876', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-4d59cc4f-88dd-4fcd-b0ba-ae648429650b', max_length=255, verbose_name='会議名'),
        ),
    ]
