# Generated by Django 4.2.16 on 2025-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0070_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-3fb9fd68-7537-4d32-980c-49053f0e83fe', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-74dd2d0b-d062-4b07-a0bc-496a03a9c60d', max_length=255, verbose_name='会議名'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='source_part_email_619ff8_idx'),
        ),
    ]
