# Generated by Django 4.2.16 on 2025-07-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0071_alter_meeting_meeting_id_alter_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meeting',
            name='source_meet_date_413d03_idx',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-82c48c15-3093-4ce4-9ca5-4af02722f34a', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-b45a739f-f110-4c8c-8ed1-7dbe054490c3', max_length=255, verbose_name='会議名'),
        ),
    ]
