# Generated by Django 4.2.16 on 2025-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0072_remove_meeting_source_meet_date_413d03_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-3c52df9f-8d4a-4794-b229-cfc5f4dd1c71', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-034a1c0a-93cc-44f2-8f4c-5b32f2511eb7', max_length=255, verbose_name='会議名'),
        ),
    ]
