# Generated by Django 4.2.16 on 2025-07-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0073_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ca47dc2b-5736-4e65-b05d-c8dadfe34d07', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-149fdd04-08f0-4324-8536-79ed49260951', max_length=255, verbose_name='会議名'),
        ),
    ]
