# Generated by Django 4.2.16 on 2025-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0074_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-356614d7-567a-46fc-a594-3bee2a73ef51', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-af67c7f9-bde8-4bbe-a880-5b22a5ab78c1', max_length=255, verbose_name='会議名'),
        ),
    ]
