# Generated by Django 4.2.16 on 2025-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0075_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-ad269248-1a26-4d60-94a3-9c6942a5a350', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-aa02c34b-036e-4ff5-bf84-12b979da8515', max_length=255, verbose_name='会議名'),
        ),
    ]
