# Generated by Django 4.2.16 on 2025-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0076_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-9ac6e169-306f-4e5d-8673-e767109cf1a1', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-466576fb-7557-4871-a059-8bf3adf13a3a', max_length=255, verbose_name='会議名'),
        ),
    ]
