# Generated by Django 4.2.16 on 2025-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0077_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-d6e75ce2-0ef0-44b1-abfb-27357e26ee26', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-8a55c906-055c-42ab-9ee0-3fd689a7d45c', max_length=255, verbose_name='会議名'),
        ),
    ]
