# Generated by Django 4.2.16 on 2025-08-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0078_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-29d352b7-8498-4637-9d3a-242515352a48', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3b2c6214-b23a-4ce5-b706-91d0670ea048', max_length=255, verbose_name='会議名'),
        ),
    ]
