# Generated by Django 4.2.16 on 2025-10-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0079_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-1f5a55db-b359-46ed-ab5c-f64ef3038f58', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-51b44a83-1332-4571-8ea5-e6a45d8b7c47', max_length=255, verbose_name='会議名'),
        ),
    ]
