# Generated by Django 4.2.16 on 2025-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0080_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-2211dcb4-fdf2-47a6-87b6-688a2c366ba4', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-e1ed31d1-72c5-4a9b-ac04-15977407ec7e', max_length=255, verbose_name='会議名'),
        ),
    ]
