# Generated by Django 4.2.16 on 2025-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0081_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-cf7c0a74-6f05-41f1-a8ba-9ff8df5eba03', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-4c695ba2-e213-434f-a085-d5b827a1ebde', max_length=255, verbose_name='会議名'),
        ),
    ]
