# Generated by Django 4.2.16 on 2025-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0082_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-bbd5b05b-86c0-4f32-a2d9-a7a8e66e6e43', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-bad59b71-da38-43c3-be0f-656d44c38c4f', max_length=255, verbose_name='会議名'),
        ),
    ]
