# Generated by Django 4.2.16 on 2025-12-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0083_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-c8c43a65-aece-48cd-af92-578a0c0590d4', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-3683e110-adbd-4316-8c10-024d2a9ed9dd', max_length=255, verbose_name='会議名'),
        ),
    ]
