# Generated by Django 4.2.16 on 2025-12-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0084_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-41e57d62-8b93-41a5-8418-bebbbef00bf6', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-2d20ad95-3a92-432a-b301-0a9a8543c157', max_length=255, verbose_name='会議名'),
        ),
    ]
