# Generated by Django 4.2.16 on 2025-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0085_alter_meeting_meeting_id_alter_meeting_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='random-c1c8967c-bec7-471d-8fb9-76953766782d', max_length=255, verbose_name='会議ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='random-9eb6d896-8d2b-439c-87ae-3e82fa99c0dd', max_length=255, verbose_name='会議名'),
        ),
    ]
